version: "3.8"

services:
  php:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./docker/php
      dockerfile: Dockerfile
    image: optimacultura-client-app
    container_name: optimacultura-client-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      optimacultura-network:

  nginx:
    image: nginx:1.17-alpine
    container_name: optimacultura-client-app-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      optimacultura-network:

  mariadb:
    image: 'mariadb:11'
    ports:
      - 3333:3306
    container_name: optimacultura-client-db
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'dummy-db'
      MYSQL_USER: 'dummy'
      MYSQL_PASSWORD: 'password'
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - optimacultura-network

volumes:
  dbdata:

networks:
  optimacultura-network:
    driver: bridge
